{% set name = "aflow" %}
{% set version = "0.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c94c20fb437f059780921244d9c6ab416278df33594b359ef0157cb1c329447b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - pytest-runner
    - pypandoc
  run:
    - python
    - pip
    - termcolor
    - numpy
    - six
    - jinja2
    - beautifulsoup4
    - ase

test:
  imports:
    - aflow
  commands:
    - pip check

about:
  home: https://github.com/rosenbrockc/aflow
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python API wrapping the AFLUX API language for AFLOW library.

  description: |
    Python API wrapping the AFLUX API language for AFLOW library. 
    Note: This is not an official repo of the AFLOW consortium and is not 
    maintained by them. API Documentation.
  doc_url: https://rosenbrockc.github.io/aflow/
  dev_url: https://github.com/rosenbrockc/aflow

extra:
  recipe-maintainers:
    - jan-janssen
